name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'profile_name'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  dbt_project:
    ingest:
      +schema: raw
      +materialized: table
    staging:
      +schema: stg
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  seeds_file_name:
    +quote_columns: false

vars:
  raw_data_path: "/workspaces/US-Tariff-What-didnt-or-did-do/data"