profile_name:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "md:{{ var('db_name', 'my_db') }}?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      threads: 4
      extensions:
        - motherduck