sources:
  - name: raw
    database: us_tariff  
    schema: raw
    tables:
      - name: us_treasury_statement_monthly
      - name: us_trade_exports_enduse_monthly
      - name: us_trade_imports_enduse_monthly
      - name: us_trade_imports_enduse_country_monthly
      - name: us_trade_exports_enduse_country_monthly
      - name: us_trade_exports_country_monthly