name: dbt_pipeline_CICD

env:
  MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
  DBT_PROJECT_DIR: ${{ github.workspace }}/pipeline

on:
  push:
    branches: [ "test-action" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-dbt-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install dbt dependencies
        run: pip install dbt-duckdb

      - name: Set dbt target output
        run: |
          echo "DBT_TARGET=prod" >> $GITHUB_ENV
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Download previous manifest
        uses: actions/download-artifact@v4
        with:
          name: previous-manifest
          path: state
        continue-on-error: true

      # - name: dbt deps
      #   run: dbt deps --target $DBT_TARGET
      #   working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: dbt build - modified
        run: |
          if [ -f state/manifest.json ]; then
            dbt build --target $DBT_TARGET --select state:modified+ --state state
          else
            dbt build --target $DBT_TARGET --exclude tag:static --exclude tag:dim
          fi
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      # - name: Generate dbt doc
      #   run: dbt docs generate
      #   working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: previous-manifest
          path: target/manifest.json
